services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    networks:
      app_network:
        ipv4_address: 172.20.0.2
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=myapp
    networks:
      app_network:
        ipv4_address: 172.20.0.3

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
          ip_range: 172.20.0.0/24
